out_dir: results
metric_best: f1
num_workers: 6
wandb:
  use: True
  project: PE_PLUS
  name: peptides_struct_gcn_dino
  entity: kisinberke 
dataset:
  format: PyG-COCOSuperpixels
  name: edge_wt_region_boundary
  slic_compactness: 30
  task: graph
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: COCONode+Dino
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: COCOEdge
  edge_encoder_bn: False
posenc_Dino:
  enable: True
  save_folder: Dino
  model_name: log-rwth-aachen/dinov1_shufflingtest
  aggr: sum
  model: Linear
  raw_norm_type: BatchNorm
  dim_pe_in: 384
  dim_pe: 32
train:
  mode: custom
  batch_size: 50
  eval_period: 1
  ckpt_period: 100
  eval_smoothing_metrics: True
model:
  type: custom_gnn
  loss_fun: weighted_cross_entropy
gnn:
  head: inductive_node
  layers_pre_mp: 0
  layers_mp: 18
  layers_post_mp: 1
  layer_type: gcne
  dim_inner: 70
  act: gelu
  dropout: 0.05
  agg: mean
  normalize_adj: False
  ffn: True
  residual: True
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 300
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
