out_dir: results
metric_best: f1
wandb:
  use: True
  project: PE_PLUS
  name: ogbg_code2_dino
  entity: kisinberke 
dataset:
  format: OGB
  name: ogbg-code2
  task: graph
  task_type: subtoken_prediction
  transductive: False
  node_encoder: True
  node_encoder_name: ASTNode+Dino
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: ASTEdge
  edge_encoder_bn: False
posenc_Dino:
  enable: True
  save_folder: Dino
  model_name: log-rwth-aachen/dinov1_shufflingtest
  aggr: sum
  model: Linear
  raw_norm_type: BatchNorm
  dim_pe_in: 384
  dim_pe: 32
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: custom_gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: mean
gnn:
  head: ogb_code_graph
  layer_type: gatedgcn
  layers_mp: 5
  layers_pre_mp: 0
  layers_post_mp: 3
  dim_inner: 512
  batchnorm: True
  act: relu
  dropout: 0.2
  agg: mean
  normalize_adj: False
  ffn: True
  residual: True
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-6
  base_lr: 0.0001
  max_epoch: 30
  scheduler: cosine_with_warmup
  num_warmup_epochs: 2