out_dir: results
metric_best: ap
wandb:
  use: True
  project: PE_PLUS
  name: peptides_func_gcn_dino
  entity: kisinberke 
dataset:
  format: OGB
  name: peptides-functional
  task: graph
  task_type: classification_multilabel
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+Dino
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_Dino:
  enable: True
  save_folder: Dino
  model_name: log-rwth-aachen/dinov1_shufflingtest
  aggr: sum
  model: Linear
  raw_norm_type: BatchNorm
  dim_pe_in: 384
  dim_pe: 32
train:
  mode: custom
  batch_size: 16
  eval_period: 1
  ckpt_period: 100
model:
  type: custom_gnn
  loss_fun: cross_entropy
  graph_pooling: mean
gnn:
  head: mlp_graph
  ffn: False
  layers_pre_mp: 0
  layers_mp: 3
  layers_post_mp: 4
  dim_inner: 275
  layer_type: gcne
  act: gelu
  residual: False
  dropout: 0.2
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 300
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
