out_dir: results
metric_best: mae
metric_agg: argmin
wandb:
  use: True
  project: ZINC
  name: test
  entity: kisinberke 
dataset:
  format: PyG-ZINC
  name: subset
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode+RWSE
  node_encoder_num_types: 21
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 4
  edge_encoder_bn: False
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,21)
  model: Linear
  dim_pe: 28
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: custom_gnn
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
gnn:
  head: san_graph
  layer_type: gatedgcn
  layers_mp: 9
  layers_pre_mp: 0
  layers_post_mp: 3
  dim_inner: 70
  act: relu
  dropout: 0.05
  agg: mean
  normalize_adj: False
  ffn: True
  residual: True
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.001
  max_epoch: 2000
  scheduler: cosine_with_warmup
  num_warmup_epochs: 50
  min_lr: 1e-6
